version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
      - "5173:5173"
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
